[package]
name = "Project name"
version = "1.0.0"
description = "A ferrite project"
authors = ["Author name"]
bp_folder = "./packs/BP"
rp_folder = "./packs/RP"

[dependencies.test]
url = "https://test.com/test"
version = "1.3.4"
remove_if_orphaned = false
